main: io.github.harperkdavis.MCTMain
name: minecraft-tournament
author: Harper Davis
description: None
version: 0.1.2

commands:
  mct:
    description: The main minecraft tournament command
    usage: /mct help